### ISSUE TITLE
enoding special characters

### ISSUE THREAD

**Issue by vv01f** [stura-htw-dresden/Basiswissen_E-Mail#6]
Deutsche Umlaute werden derzeit in asbach-uralter Manier escaped kodiert obwohl das input-ecoding auf utf8 steht.

* [ ] ersetzen des escaping durch simple zeichen entsprechend utf8

**Comment by shithead** [comment]
sorry habe keine umlaute auf der tastertur :D

**Comment by vv01f** [comment]
im Zweifel auch nicht notwendig: `sed 's/\\"a/ä/g;s/\\"o/ö/g;s/\\"u/ü/g;s/\\"A/Ä/g;s/\\"O/Ö/g;s/\\"U/Ü/g;s/{\\ss}/ß/ig;s/\\ss/ß/ig' *.tex`
